CREATE TABLE regions (
  regionid  INTEGER PRIMARY KEY AUTOINCREMENT,
  region    VARCHAR
);

CREATE TABLE cities (
  cityid    INTEGER PRIMARY KEY AUTOINCREMENT,
  city      VARCHAR,
  regionid  INTEGER,
  FOREIGN KEY(regionid) REFERENCES regions(regionid)
);

CREATE TABLE persons (
  personid    INTEGER PRIMARY KEY AUTOINCREMENT,
  firstname   VARCHAR,
  lastname    VARCHAR,
  middlename  VARCHAR,
  regionid    INTEGER,
  cityid      INTEGER,
  phone       VARCHAR,
  email       VARCHAR,
  comment     TEXT,
  FOREIGN KEY(regionid) REFERENCES regions(regionid),
  FOREIGN KEY(cityid)   REFERENCES cities(cityid)
);


INSERT INTO regions(region) VALUES('Sakha Republic');
INSERT INTO regions(region) VALUES('Rostov Oblast');
INSERT INTO regions(region) VALUES('Karelia');
INSERT INTO regions(region) VALUES('Republic of Adygea');
INSERT INTO regions(region) VALUES('Novgorod Oblast');
INSERT INTO regions(region) VALUES('Khanty-Mansi Autonomous Okrug');
INSERT INTO regions(region) VALUES('Nizhny Novgorod Oblast');
INSERT INTO regions(region) VALUES('Chelyabinsk Oblast');
INSERT INTO regions(region) VALUES('Volgograd Oblast');
INSERT INTO regions(region) VALUES('Saint Petersburg');
INSERT INTO regions(region) VALUES('Zabaykalsky Krai');
INSERT INTO regions(region) VALUES('Vladimir Oblast');
INSERT INTO regions(region) VALUES('Arkhangelsk Oblast');
INSERT INTO regions(region) VALUES('Jewish Autonomous Oblast');
INSERT INTO regions(region) VALUES('Kursk Oblast');
INSERT INTO regions(region) VALUES('Krasnoyarsk Krai');
INSERT INTO regions(region) VALUES('Karachay-Cherkessia');
INSERT INTO regions(region) VALUES('Yamalo-Nenets Autonomous Okrug');
INSERT INTO regions(region) VALUES('Sakhalin Oblast');
INSERT INTO regions(region) VALUES('Omsk Oblast');
INSERT INTO regions(region) VALUES('Kaluga Oblast');
INSERT INTO regions(region) VALUES('Belgorod Oblast');
INSERT INTO regions(region) VALUES('Kalmykia');
INSERT INTO regions(region) VALUES('Tomsk Oblast');
INSERT INTO regions(region) VALUES('Republic of Bashkortostan');
INSERT INTO regions(region) VALUES('Oryol Oblast');
INSERT INTO regions(region) VALUES('Kaliningrad Oblast');
INSERT INTO regions(region) VALUES('Moscow');
INSERT INTO regions(region) VALUES('Leningrad Oblast');
INSERT INTO regions(region) VALUES('Tyumen Oblast');
INSERT INTO regions(region) VALUES('Astrakhan Oblast');
INSERT INTO regions(region) VALUES('Tuva Republic');
INSERT INTO regions(region) VALUES('Tver Oblast');
INSERT INTO regions(region) VALUES('Altai Krai');
INSERT INTO regions(region) VALUES('Tula Oblast');
INSERT INTO regions(region) VALUES('Nenets Autonomous Okrug');
INSERT INTO regions(region) VALUES('Kamchatka Krai');
INSERT INTO regions(region) VALUES('Mari El');
INSERT INTO regions(region) VALUES('Magadan Oblast');
INSERT INTO regions(region) VALUES('Orenburg Oblast');
INSERT INTO regions(region) VALUES('Smolensk Oblast');
INSERT INTO regions(region) VALUES('Altai Republic');
INSERT INTO regions(region) VALUES('Udmurtia');
INSERT INTO regions(region) VALUES('Khabarovsk Krai');
INSERT INTO regions(region) VALUES('Chuvash Republic');
INSERT INTO regions(region) VALUES('Saratov Oblast');
INSERT INTO regions(region) VALUES('Dagestan');
INSERT INTO regions(region) VALUES('Stavropol Krai');
INSERT INTO regions(region) VALUES('Kirov Oblast');
INSERT INTO regions(region) VALUES('Kurgan Oblast');
INSERT INTO regions(region) VALUES('Vologda Oblast');
INSERT INTO regions(region) VALUES('Sverdlovsk Oblast');
INSERT INTO regions(region) VALUES('Murmansk Oblast');
INSERT INTO regions(region) VALUES('Ivanovo Oblast');
INSERT INTO regions(region) VALUES('Republic of Buryatia');
INSERT INTO regions(region) VALUES('Komi Republic');
INSERT INTO regions(region) VALUES('Krasnodar Krai');
INSERT INTO regions(region) VALUES('Bryansk Oblast');
INSERT INTO regions(region) VALUES('Chukotka Autonomous Okrug');
INSERT INTO regions(region) VALUES('Moscow Oblast');
INSERT INTO regions(region) VALUES('Yaroslavl Oblast');
INSERT INTO regions(region) VALUES('Samara Oblast');
INSERT INTO regions(region) VALUES('Republic of Tatarstan');
INSERT INTO regions(region) VALUES('Penza Oblast');
INSERT INTO regions(region) VALUES('Ryazan Oblast');
INSERT INTO regions(region) VALUES('Republic of Mordovia');
INSERT INTO regions(region) VALUES('Perm Krai');
INSERT INTO regions(region) VALUES('Lipetsk Oblast');
INSERT INTO regions(region) VALUES('Republic of Khakassia');
INSERT INTO regions(region) VALUES('Amur Oblast');
INSERT INTO regions(region) VALUES('Ingushetia');
INSERT INTO regions(region) VALUES('Voronezh Oblast');
INSERT INTO regions(region) VALUES('Chechen Republic');
INSERT INTO regions(region) VALUES('Kostroma Oblast');
INSERT INTO regions(region) VALUES('Pskov Oblast');
INSERT INTO regions(region) VALUES('Primorsky Krai');
INSERT INTO regions(region) VALUES('Irkutsk Oblast');
INSERT INTO regions(region) VALUES('Tambov Oblast');
INSERT INTO regions(region) VALUES('Kemerovo Oblast');
INSERT INTO regions(region) VALUES('Kabardino-Balkar Republic');
INSERT INTO regions(region) VALUES('Ulyanovsk Oblast');
INSERT INTO regions(region) VALUES('Novosibirsk Oblast');
INSERT INTO regions(region) VALUES('Republic of North Ossetia–Alania');


INSERT INTO cities(city, regionid) VALUES('Lensk', 1);
INSERT INTO cities(city, regionid) VALUES('Mirny', 1);
INSERT INTO cities(city, regionid) VALUES('Neryungri', 1);
INSERT INTO cities(city, regionid) VALUES('Nyurba', 1);
INSERT INTO cities(city, regionid) VALUES('Olyokminsk', 1);
INSERT INTO cities(city, regionid) VALUES('Pokrovsk', 1);
INSERT INTO cities(city, regionid) VALUES('Srednekolymsk', 1);
INSERT INTO cities(city, regionid) VALUES('Tommot', 1);
INSERT INTO cities(city, regionid) VALUES('Udachny', 1);
INSERT INTO cities(city, regionid) VALUES('Verkhoyansk', 1);
INSERT INTO cities(city, regionid) VALUES('Vilyuysk', 1);
INSERT INTO cities(city, regionid) VALUES('Yakutsk', 1);

INSERT INTO cities(city, regionid) VALUES('Azov', 2);
INSERT INTO cities(city, regionid) VALUES('Bataysk', 2);
INSERT INTO cities(city, regionid) VALUES('Belaya Kalitva', 2);
INSERT INTO cities(city, regionid) VALUES('Donetsk', 2);
INSERT INTO cities(city, regionid) VALUES('Gukovo', 2);
INSERT INTO cities(city, regionid) VALUES('Kamensk-Shakhtinsky', 2);
INSERT INTO cities(city, regionid) VALUES('Konstantinovsk', 2);
INSERT INTO cities(city, regionid) VALUES('Krasny Sulin', 2);
INSERT INTO cities(city, regionid) VALUES('Millerovo', 2);
INSERT INTO cities(city, regionid) VALUES('Morozovsk', 2);
INSERT INTO cities(city, regionid) VALUES('Novocherkassk', 2);
INSERT INTO cities(city, regionid) VALUES('Novoshakhtinsk', 2);
INSERT INTO cities(city, regionid) VALUES('Proletarsk', 2);
INSERT INTO cities(city, regionid) VALUES('Rostov-on-Don', 2);
INSERT INTO cities(city, regionid) VALUES('Salsk', 2);
INSERT INTO cities(city, regionid) VALUES('Semikarakorsk', 2);
INSERT INTO cities(city, regionid) VALUES('Shakhty', 2);
INSERT INTO cities(city, regionid) VALUES('Taganrog', 2);
INSERT INTO cities(city, regionid) VALUES('Tsimlyansk', 2);
INSERT INTO cities(city, regionid) VALUES('Volgodonsk', 2);
INSERT INTO cities(city, regionid) VALUES('Zernograd', 2);
INSERT INTO cities(city, regionid) VALUES('Zverevo', 2);

INSERT INTO cities(city, regionid) VALUES('Kem', 3);
INSERT INTO cities(city, regionid) VALUES('Kondopoga', 3);
INSERT INTO cities(city, regionid) VALUES('Kostomuksha', 3);
INSERT INTO cities(city, regionid) VALUES('Lakhdenpokhya', 3);
INSERT INTO cities(city, regionid) VALUES('Medvezhyegorsk', 3);
INSERT INTO cities(city, regionid) VALUES('Olonets', 3);
INSERT INTO cities(city, regionid) VALUES('Petrozavodsk', 3);
INSERT INTO cities(city, regionid) VALUES('Pitkyaranta', 3);
INSERT INTO cities(city, regionid) VALUES('Pudozh', 3);
INSERT INTO cities(city, regionid) VALUES('Segezha', 3);
INSERT INTO cities(city, regionid) VALUES('Sortavala', 3);
INSERT INTO cities(city, regionid) VALUES('Suoyarvi', 3);

INSERT INTO cities(city, regionid) VALUES('Maykop', 4);

INSERT INTO cities(city, regionid) VALUES('Chudovo', 5);
INSERT INTO cities(city, regionid) VALUES('Kholm', 5);
INSERT INTO cities(city, regionid) VALUES('Malaya Vishera', 5);
INSERT INTO cities(city, regionid) VALUES('Okulovka', 5);
INSERT INTO cities(city, regionid) VALUES('Pestovo', 5);
INSERT INTO cities(city, regionid) VALUES('Soltsy', 5);
INSERT INTO cities(city, regionid) VALUES('Staraya Russa', 5);
INSERT INTO cities(city, regionid) VALUES('Valday', 5);
INSERT INTO cities(city, regionid) VALUES('Veliky Novgorod', 5);

INSERT INTO cities(city, regionid) VALUES('Khanty-Mansiysk', 6);
INSERT INTO cities(city, regionid) VALUES('Kogalym', 6);
INSERT INTO cities(city, regionid) VALUES('Langepas', 6);
INSERT INTO cities(city, regionid) VALUES('Lyantor', 6);
INSERT INTO cities(city, regionid) VALUES('Megion', 6);
INSERT INTO cities(city, regionid) VALUES('Nefteyugansk', 6);
INSERT INTO cities(city, regionid) VALUES('Nizhnevartovsk', 6);
INSERT INTO cities(city, regionid) VALUES('Nyagan', 6);
INSERT INTO cities(city, regionid) VALUES('Pokachi', 6);
INSERT INTO cities(city, regionid) VALUES('Pyt-Yakh', 6);
INSERT INTO cities(city, regionid) VALUES('Raduzhny', 6);
INSERT INTO cities(city, regionid) VALUES('Sovetsky', 6);
INSERT INTO cities(city, regionid) VALUES('Surgut', 6);
INSERT INTO cities(city, regionid) VALUES('Uray', 6);
INSERT INTO cities(city, regionid) VALUES('Yugorsk', 6);

INSERT INTO cities(city, regionid) VALUES('Balakhna', 7);
INSERT INTO cities(city, regionid) VALUES('Bogorodsk', 7);
INSERT INTO cities(city, regionid) VALUES('Bor', 7);
INSERT INTO cities(city, regionid) VALUES('Chkalovsk', 7);
INSERT INTO cities(city, regionid) VALUES('Dzerzhinsk', 7);
INSERT INTO cities(city, regionid) VALUES('Gorbatov', 7);
INSERT INTO cities(city, regionid) VALUES('Gorodets', 7);
INSERT INTO cities(city, regionid) VALUES('Knyaginino', 7);
INSERT INTO cities(city, regionid) VALUES('Kstovo', 7);
INSERT INTO cities(city, regionid) VALUES('Kulebaki', 7);
INSERT INTO cities(city, regionid) VALUES('Lukoyanov', 7);
INSERT INTO cities(city, regionid) VALUES('Lyskovo', 7);
INSERT INTO cities(city, regionid) VALUES('Navashino', 7);
INSERT INTO cities(city, regionid) VALUES('Nizhny Novgorod', 7);
INSERT INTO cities(city, regionid) VALUES('Pavlovo', 7);
INSERT INTO cities(city, regionid) VALUES('Perevoz', 7);
INSERT INTO cities(city, regionid) VALUES('Pervomaysk', 7);
INSERT INTO cities(city, regionid) VALUES('Sarov', 7);
INSERT INTO cities(city, regionid) VALUES('Semyonov', 7);
INSERT INTO cities(city, regionid) VALUES('Sergach', 7);
INSERT INTO cities(city, regionid) VALUES('Shakhunya', 7);
INSERT INTO cities(city, regionid) VALUES('Uren', 7);
INSERT INTO cities(city, regionid) VALUES('Vetluga', 7);
INSERT INTO cities(city, regionid) VALUES('Volodarsk', 7);
INSERT INTO cities(city, regionid) VALUES('Vorsma', 7);
INSERT INTO cities(city, regionid) VALUES('Vyksa', 7);
INSERT INTO cities(city, regionid) VALUES('Zavolzhye', 7);

INSERT INTO cities(city, regionid) VALUES('Bakal', 8);
INSERT INTO cities(city, regionid) VALUES('Chebarkul', 8);
INSERT INTO cities(city, regionid) VALUES('Chelyabinsk', 8);
INSERT INTO cities(city, regionid) VALUES('Karabash', 8);
INSERT INTO cities(city, regionid) VALUES('Kartaly', 8);
INSERT INTO cities(city, regionid) VALUES('Kasli', 8);
INSERT INTO cities(city, regionid) VALUES('Katav-Ivanovsk', 8);
INSERT INTO cities(city, regionid) VALUES('Kopeysk', 8);
INSERT INTO cities(city, regionid) VALUES('Korkino', 8);
INSERT INTO cities(city, regionid) VALUES('Kusa', 8);
INSERT INTO cities(city, regionid) VALUES('Kyshtym', 8);
INSERT INTO cities(city, regionid) VALUES('Magnitogorsk', 8);
INSERT INTO cities(city, regionid) VALUES('Miass', 8);
INSERT INTO cities(city, regionid) VALUES('Minyar', 8);
INSERT INTO cities(city, regionid) VALUES('Nyazepetrovsk', 8);
INSERT INTO cities(city, regionid) VALUES('Ozyorsk', 8);
INSERT INTO cities(city, regionid) VALUES('Plast', 8);
INSERT INTO cities(city, regionid) VALUES('Satka', 8);
INSERT INTO cities(city, regionid) VALUES('Sim', 8);
INSERT INTO cities(city, regionid) VALUES('Snezhinsk', 8);
INSERT INTO cities(city, regionid) VALUES('Troitsk', 8);
INSERT INTO cities(city, regionid) VALUES('Tryokhgorny', 8);
INSERT INTO cities(city, regionid) VALUES('Ust-Katav', 8);
INSERT INTO cities(city, regionid) VALUES('Verkhneuralsk', 8);
INSERT INTO cities(city, regionid) VALUES('Verkhny Ufaley', 8);
INSERT INTO cities(city, regionid) VALUES('Yemanzhelinsk', 8);
INSERT INTO cities(city, regionid) VALUES('Yuryuzan', 8);
INSERT INTO cities(city, regionid) VALUES('Yuzhnouralsk', 8);
INSERT INTO cities(city, regionid) VALUES('Zlatoust', 8);

INSERT INTO cities(city, regionid) VALUES('Frolovo', 9);
INSERT INTO cities(city, regionid) VALUES('Kalach-na-Donu', 9);
INSERT INTO cities(city, regionid) VALUES('Kamyshin', 9);
INSERT INTO cities(city, regionid) VALUES('Kotelnikovo', 9);
INSERT INTO cities(city, regionid) VALUES('Kotovo', 9);
INSERT INTO cities(city, regionid) VALUES('Krasnoslobodsk', 9);
INSERT INTO cities(city, regionid) VALUES('Leninsk', 9);
INSERT INTO cities(city, regionid) VALUES('Mikhaylovka', 9);
INSERT INTO cities(city, regionid) VALUES('Nikolayevsk', 9);
INSERT INTO cities(city, regionid) VALUES('Novoanninsky', 9);
INSERT INTO cities(city, regionid) VALUES('Pallasovka', 9);
INSERT INTO cities(city, regionid) VALUES('Petrov Val', 9);
INSERT INTO cities(city, regionid) VALUES('Serafimovich', 9);
INSERT INTO cities(city, regionid) VALUES('Surovikino', 9);
INSERT INTO cities(city, regionid) VALUES('Uryupinsk', 9);
INSERT INTO cities(city, regionid) VALUES('Volgograd', 9);
INSERT INTO cities(city, regionid) VALUES('Volzhsky', 9);
INSERT INTO cities(city, regionid) VALUES('Zhirnovsk', 9);

INSERT INTO cities(city, regionid) VALUES('Krasnoye Selo', 10);
INSERT INTO cities(city, regionid) VALUES('Kronstadt', 10);
INSERT INTO cities(city, regionid) VALUES('Lomonosov', 10);
INSERT INTO cities(city, regionid) VALUES('Pavlovsk', 10);
INSERT INTO cities(city, regionid) VALUES('Petergof', 10);
INSERT INTO cities(city, regionid) VALUES('Pushkin', 10);
INSERT INTO cities(city, regionid) VALUES('Saint Petersburg', 10);
INSERT INTO cities(city, regionid) VALUES('Sestroretsk', 10);
INSERT INTO cities(city, regionid) VALUES('Zelenogorsk', 10);

INSERT INTO cities(city, regionid) VALUES('Borzya', 11);
INSERT INTO cities(city, regionid) VALUES('Chita', 11);
INSERT INTO cities(city, regionid) VALUES('Khilok', 11);
INSERT INTO cities(city, regionid) VALUES('Krasnokamensk', 11);
INSERT INTO cities(city, regionid) VALUES('Mogocha', 11);
INSERT INTO cities(city, regionid) VALUES('Nerchinsk', 11);
INSERT INTO cities(city, regionid) VALUES('Petrovsk-Zabaykalsky', 11);
INSERT INTO cities(city, regionid) VALUES('Shilka', 11);
INSERT INTO cities(city, regionid) VALUES('Sretensk', 11);

INSERT INTO cities(city, regionid) VALUES('Gorokhovets', 12);
INSERT INTO cities(city, regionid) VALUES('Gus-Khrustalny', 12);
INSERT INTO cities(city, regionid) VALUES('Kameshkovo', 12);
INSERT INTO cities(city, regionid) VALUES('Karabanovo', 12);
INSERT INTO cities(city, regionid) VALUES('Kirzhach', 12);
INSERT INTO cities(city, regionid) VALUES('Kolchugino', 12);
INSERT INTO cities(city, regionid) VALUES('Kosteryovo', 12);
INSERT INTO cities(city, regionid) VALUES('Kovrov', 12);
INSERT INTO cities(city, regionid) VALUES('Kurlovo', 12);
INSERT INTO cities(city, regionid) VALUES('Lakinsk', 12);
INSERT INTO cities(city, regionid) VALUES('Melenki', 12);
INSERT INTO cities(city, regionid) VALUES('Murom', 12);
INSERT INTO cities(city, regionid) VALUES('Petushki', 12);
INSERT INTO cities(city, regionid) VALUES('Pokrov', 12);
INSERT INTO cities(city, regionid) VALUES('Raduzhny', 12);
INSERT INTO cities(city, regionid) VALUES('Sobinka', 12);
INSERT INTO cities(city, regionid) VALUES('Strunino', 12);
INSERT INTO cities(city, regionid) VALUES('Sudogda', 12);
INSERT INTO cities(city, regionid) VALUES('Suzdal', 12);
INSERT INTO cities(city, regionid) VALUES('Vladimir', 12);
INSERT INTO cities(city, regionid) VALUES('Vyazniki', 12);
INSERT INTO cities(city, regionid) VALUES('Yuryev-Polsky', 12);

INSERT INTO cities(city, regionid) VALUES('Kargopol', 13);
INSERT INTO cities(city, regionid) VALUES('Koryazhma', 13);
INSERT INTO cities(city, regionid) VALUES('Kotlas', 13);
INSERT INTO cities(city, regionid) VALUES('Mezen', 13);
INSERT INTO cities(city, regionid) VALUES('Mirny', 13);
INSERT INTO cities(city, regionid) VALUES('Novodvinsk', 13);
INSERT INTO cities(city, regionid) VALUES('Nyandoma', 13);
INSERT INTO cities(city, regionid) VALUES('Onega', 13);
INSERT INTO cities(city, regionid) VALUES('Severodvinsk', 13);
INSERT INTO cities(city, regionid) VALUES('Shenkursk', 13);
INSERT INTO cities(city, regionid) VALUES('Solvychegodsk', 13);
INSERT INTO cities(city, regionid) VALUES('Velsk', 13);

INSERT INTO cities(city, regionid) VALUES('Obluchye', 14);

INSERT INTO cities(city, regionid) VALUES('Fatezh', 15);
INSERT INTO cities(city, regionid) VALUES('Kurchatov', 15);
INSERT INTO cities(city, regionid) VALUES('Kursk', 15);
INSERT INTO cities(city, regionid) VALUES('Lgov', 15);
INSERT INTO cities(city, regionid) VALUES('Oboyan', 15);
INSERT INTO cities(city, regionid) VALUES('Rylsk', 15);
INSERT INTO cities(city, regionid) VALUES('Shchigry', 15);
INSERT INTO cities(city, regionid) VALUES('Sudzha', 15);
INSERT INTO cities(city, regionid) VALUES('Zheleznogorsk', 15);

INSERT INTO cities(city, regionid) VALUES('Artyomovsk', 16);
INSERT INTO cities(city, regionid) VALUES('Bogotol', 16);
INSERT INTO cities(city, regionid) VALUES('Borodino', 16);
INSERT INTO cities(city, regionid) VALUES('Divnogorsk', 16);
INSERT INTO cities(city, regionid) VALUES('Dudinka', 16);
INSERT INTO cities(city, regionid) VALUES('Igarka', 16);
INSERT INTO cities(city, regionid) VALUES('Ilansky', 16);
INSERT INTO cities(city, regionid) VALUES('Kansk', 16);
INSERT INTO cities(city, regionid) VALUES('Kodinsk', 16);
INSERT INTO cities(city, regionid) VALUES('Krasnoyarsk', 16);
INSERT INTO cities(city, regionid) VALUES('Lesosibirsk', 16);
INSERT INTO cities(city, regionid) VALUES('Minusinsk', 16);
INSERT INTO cities(city, regionid) VALUES('Nazarovo', 16);
INSERT INTO cities(city, regionid) VALUES('Norilsk', 16);
INSERT INTO cities(city, regionid) VALUES('Sharypovo', 16);
INSERT INTO cities(city, regionid) VALUES('Sosnovoborsk', 16);
INSERT INTO cities(city, regionid) VALUES('Uyar', 16);
INSERT INTO cities(city, regionid) VALUES('Uzhur', 16);
INSERT INTO cities(city, regionid) VALUES('Yeniseysk', 16);
INSERT INTO cities(city, regionid) VALUES('Zaozyorny', 16);
INSERT INTO cities(city, regionid) VALUES('Zelenogorsk', 16);
INSERT INTO cities(city, regionid) VALUES('Zheleznogorsk', 16);

INSERT INTO cities(city, regionid) VALUES('Karachayevsk', 17);
INSERT INTO cities(city, regionid) VALUES('Teberda', 17);
INSERT INTO cities(city, regionid) VALUES('Ust-Dzheguta', 17);

INSERT INTO cities(city, regionid) VALUES('Labytnangi', 18);
INSERT INTO cities(city, regionid) VALUES('Muravlenko', 18);
INSERT INTO cities(city, regionid) VALUES('Nadym', 18);
INSERT INTO cities(city, regionid) VALUES('Novy Urengoy', 18);
INSERT INTO cities(city, regionid) VALUES('Noyabrsk', 18);
INSERT INTO cities(city, regionid) VALUES('Salekhard', 18);
INSERT INTO cities(city, regionid) VALUES('Tarko-Sale', 18);

INSERT INTO cities(city, regionid) VALUES('Aniva', 19);
INSERT INTO cities(city, regionid) VALUES('Dolinsk', 19);
INSERT INTO cities(city, regionid) VALUES('Kholmsk', 19);
INSERT INTO cities(city, regionid) VALUES('Korsakov', 19);
INSERT INTO cities(city, regionid) VALUES('Kurilsk', 19);
INSERT INTO cities(city, regionid) VALUES('Makarov', 19);
INSERT INTO cities(city, regionid) VALUES('Nevelsk', 19);
INSERT INTO cities(city, regionid) VALUES('Okha', 19);
INSERT INTO cities(city, regionid) VALUES('Poronaysk', 19);
INSERT INTO cities(city, regionid) VALUES('Severo-Kurilsk', 19);
INSERT INTO cities(city, regionid) VALUES('Shakhtyorsk', 19);
INSERT INTO cities(city, regionid) VALUES('Tomari', 19);
INSERT INTO cities(city, regionid) VALUES('Uglegorsk', 19);
INSERT INTO cities(city, regionid) VALUES('Yuzhno-Sakhalinsk', 19);

INSERT INTO cities(city, regionid) VALUES('Kalachinsk', 20);
INSERT INTO cities(city, regionid) VALUES('Nazyvayevsk', 20);
INSERT INTO cities(city, regionid) VALUES('Omsk', 20);
INSERT INTO cities(city, regionid) VALUES('Tara', 20);
INSERT INTO cities(city, regionid) VALUES('Tyukalinsk', 20);

INSERT INTO cities(city, regionid) VALUES('Belousovo', 21);
INSERT INTO cities(city, regionid) VALUES('Borovsk', 21);
INSERT INTO cities(city, regionid) VALUES('Kaluga', 21);
INSERT INTO cities(city, regionid) VALUES('Kirov', 21);
INSERT INTO cities(city, regionid) VALUES('Kondrovo', 21);
INSERT INTO cities(city, regionid) VALUES('Kozelsk', 21);
INSERT INTO cities(city, regionid) VALUES('Kremyonki', 21);
INSERT INTO cities(city, regionid) VALUES('Lyudinovo', 21);
INSERT INTO cities(city, regionid) VALUES('Maloyaroslavets', 21);
INSERT INTO cities(city, regionid) VALUES('Medyn', 21);
INSERT INTO cities(city, regionid) VALUES('Meshchovsk', 21);
INSERT INTO cities(city, regionid) VALUES('Mosalsk', 21);
INSERT INTO cities(city, regionid) VALUES('Obninsk', 21);
INSERT INTO cities(city, regionid) VALUES('Sosensky', 21);
INSERT INTO cities(city, regionid) VALUES('Spas-Demensk', 21);
INSERT INTO cities(city, regionid) VALUES('Sukhinichi', 21);
INSERT INTO cities(city, regionid) VALUES('Tarusa', 21);
INSERT INTO cities(city, regionid) VALUES('Yermolino', 21);
INSERT INTO cities(city, regionid) VALUES('Yukhnov', 21);
INSERT INTO cities(city, regionid) VALUES('Zhizdra', 21);
INSERT INTO cities(city, regionid) VALUES('Zhukov', 21);

INSERT INTO cities(city, regionid) VALUES('Belgorod', 22);
INSERT INTO cities(city, regionid) VALUES('Biryuch', 22);
INSERT INTO cities(city, regionid) VALUES('Grayvoron', 22);
INSERT INTO cities(city, regionid) VALUES('Gubkin', 22);
INSERT INTO cities(city, regionid) VALUES('Korocha', 22);
INSERT INTO cities(city, regionid) VALUES('Novy Oskol', 22);
INSERT INTO cities(city, regionid) VALUES('Shebekino', 22);
INSERT INTO cities(city, regionid) VALUES('Stary Oskol', 22);
INSERT INTO cities(city, regionid) VALUES('Stroitel', 22);
INSERT INTO cities(city, regionid) VALUES('Valuyki', 22);

INSERT INTO cities(city, regionid) VALUES('Gorodovikovsk', 23);
INSERT INTO cities(city, regionid) VALUES('Lagan', 23);

INSERT INTO cities(city, regionid) VALUES('Kedrovy', 24);
INSERT INTO cities(city, regionid) VALUES('Kolpashevo', 24);
INSERT INTO cities(city, regionid) VALUES('Seversk', 24);
INSERT INTO cities(city, regionid) VALUES('Strezhevoy', 24);
INSERT INTO cities(city, regionid) VALUES('Tomsk', 24);

INSERT INTO cities(city, regionid) VALUES('Baymak', 25);
INSERT INTO cities(city, regionid) VALUES('Belebey', 25);
INSERT INTO cities(city, regionid) VALUES('Beloretsk', 25);
INSERT INTO cities(city, regionid) VALUES('Birsk', 25);
INSERT INTO cities(city, regionid) VALUES('Blagoveshchensk', 25);
INSERT INTO cities(city, regionid) VALUES('Davlekanovo', 25);
INSERT INTO cities(city, regionid) VALUES('Dyurtyuli', 25);
INSERT INTO cities(city, regionid) VALUES('Ishimbay', 25);
INSERT INTO cities(city, regionid) VALUES('Kumertau', 25);
INSERT INTO cities(city, regionid) VALUES('Meleuz', 25);
INSERT INTO cities(city, regionid) VALUES('Mezhgorye', 25);
INSERT INTO cities(city, regionid) VALUES('Neftekamsk', 25);
INSERT INTO cities(city, regionid) VALUES('Oktyabrsky', 25);
INSERT INTO cities(city, regionid) VALUES('Salavat', 25);
INSERT INTO cities(city, regionid) VALUES('Sibay', 25);
INSERT INTO cities(city, regionid) VALUES('Sterlitamak', 25);
INSERT INTO cities(city, regionid) VALUES('Tuymazy', 25);
INSERT INTO cities(city, regionid) VALUES('Uchaly', 25);
INSERT INTO cities(city, regionid) VALUES('Ufa', 25);
INSERT INTO cities(city, regionid) VALUES('Yanaul', 25);

INSERT INTO cities(city, regionid) VALUES('Dmitrovsk', 26);
INSERT INTO cities(city, regionid) VALUES('Livny', 26);
INSERT INTO cities(city, regionid) VALUES('Maloarkhangelsk', 26);
INSERT INTO cities(city, regionid) VALUES('Mtsensk', 26);
INSERT INTO cities(city, regionid) VALUES('Novosil', 26);
INSERT INTO cities(city, regionid) VALUES('Oryol', 26);

INSERT INTO cities(city, regionid) VALUES('Baltiysk', 27);
INSERT INTO cities(city, regionid) VALUES('Chernyakhovsk', 27);
INSERT INTO cities(city, regionid) VALUES('Guryevsk', 27);
INSERT INTO cities(city, regionid) VALUES('Gusev', 27);
INSERT INTO cities(city, regionid) VALUES('Gvardeysk', 27);
INSERT INTO cities(city, regionid) VALUES('Kaliningrad', 27);
INSERT INTO cities(city, regionid) VALUES('Krasnoznamensk', 27);
INSERT INTO cities(city, regionid) VALUES('Ladushkin', 27);
INSERT INTO cities(city, regionid) VALUES('Mamonovo', 27);
INSERT INTO cities(city, regionid) VALUES('Neman', 27);
INSERT INTO cities(city, regionid) VALUES('Nesterov', 27);
INSERT INTO cities(city, regionid) VALUES('Ozyorsk', 27);
INSERT INTO cities(city, regionid) VALUES('Pionersky', 27);
INSERT INTO cities(city, regionid) VALUES('Polessk', 27);
INSERT INTO cities(city, regionid) VALUES('Pravdinsk', 27);
INSERT INTO cities(city, regionid) VALUES('Slavsk', 27);
INSERT INTO cities(city, regionid) VALUES('Sovetsk', 27);
INSERT INTO cities(city, regionid) VALUES('Svetlogorsk', 27);
INSERT INTO cities(city, regionid) VALUES('Svetly', 27);
INSERT INTO cities(city, regionid) VALUES('Zelenogradsk', 27);

INSERT INTO cities(city, regionid) VALUES('Moscow', 28);
INSERT INTO cities(city, regionid) VALUES('Troitsk', 28);
INSERT INTO cities(city, regionid) VALUES('Zelenograd', 28);

INSERT INTO cities(city, regionid) VALUES('Gatchina', 29);
INSERT INTO cities(city, regionid) VALUES('Ivangorod', 29);
INSERT INTO cities(city, regionid) VALUES('Kamennogorsk', 29);
INSERT INTO cities(city, regionid) VALUES('Kingisepp', 29);
INSERT INTO cities(city, regionid) VALUES('Kirishi', 29);
INSERT INTO cities(city, regionid) VALUES('Kirovsk', 29);
INSERT INTO cities(city, regionid) VALUES('Kommunar', 29);
INSERT INTO cities(city, regionid) VALUES('Lodeynoye Pole', 29);
INSERT INTO cities(city, regionid) VALUES('Luga', 29);
INSERT INTO cities(city, regionid) VALUES('Lyuban', 29);
INSERT INTO cities(city, regionid) VALUES('Nikolskoye', 29);
INSERT INTO cities(city, regionid) VALUES('Novaya Ladoga', 29);
INSERT INTO cities(city, regionid) VALUES('Otradnoye', 29);
INSERT INTO cities(city, regionid) VALUES('Pikalyovo', 29);
INSERT INTO cities(city, regionid) VALUES('Podporozhye', 29);
INSERT INTO cities(city, regionid) VALUES('Primorsk', 29);
INSERT INTO cities(city, regionid) VALUES('Priozersk', 29);
INSERT INTO cities(city, regionid) VALUES('Sertolovo', 29);
INSERT INTO cities(city, regionid) VALUES('Shlisselburg', 29);
INSERT INTO cities(city, regionid) VALUES('Slantsy', 29);
INSERT INTO cities(city, regionid) VALUES('Sosnovy Bor', 29);
INSERT INTO cities(city, regionid) VALUES('Svetogorsk', 29);
INSERT INTO cities(city, regionid) VALUES('Syasstroy', 29);
INSERT INTO cities(city, regionid) VALUES('Tikhvin', 29);
INSERT INTO cities(city, regionid) VALUES('Tosno', 29);
INSERT INTO cities(city, regionid) VALUES('Volkhov', 29);
INSERT INTO cities(city, regionid) VALUES('Volosovo', 29);
INSERT INTO cities(city, regionid) VALUES('Vsevolozhsk', 29);
INSERT INTO cities(city, regionid) VALUES('Vyborg', 29);
INSERT INTO cities(city, regionid) VALUES('Vysotsk', 29);

INSERT INTO cities(city, regionid) VALUES('Tobolsk', 30);
INSERT INTO cities(city, regionid) VALUES('Tyumen', 30);
INSERT INTO cities(city, regionid) VALUES('Yalutorovsk', 30);
INSERT INTO cities(city, regionid) VALUES('Zavodoukovsk', 30);

INSERT INTO cities(city, regionid) VALUES('Astrakhan', 31);
INSERT INTO cities(city, regionid) VALUES('Kamyzyak', 31);
INSERT INTO cities(city, regionid) VALUES('Kharabali', 31);
INSERT INTO cities(city, regionid) VALUES('Narimanov', 31);
INSERT INTO cities(city, regionid) VALUES('Znamensk', 31);

INSERT INTO cities(city, regionid) VALUES('Chadan', 32);
INSERT INTO cities(city, regionid) VALUES('Kyzyl', 32);
INSERT INTO cities(city, regionid) VALUES('Shagonar', 32);
INSERT INTO cities(city, regionid) VALUES('Turan', 32);

INSERT INTO cities(city, regionid) VALUES('Bely', 33);
INSERT INTO cities(city, regionid) VALUES('Bezhetsk', 33);
INSERT INTO cities(city, regionid) VALUES('Bologoye', 33);
INSERT INTO cities(city, regionid) VALUES('Kalyazin', 33);
INSERT INTO cities(city, regionid) VALUES('Kashin', 33);
INSERT INTO cities(city, regionid) VALUES('Kimry', 33);
INSERT INTO cities(city, regionid) VALUES('Konakovo', 33);
INSERT INTO cities(city, regionid) VALUES('Krasny Kholm', 33);
INSERT INTO cities(city, regionid) VALUES('Kuvshinovo', 33);
INSERT INTO cities(city, regionid) VALUES('Likhoslavl', 33);
INSERT INTO cities(city, regionid) VALUES('Nelidovo', 33);
INSERT INTO cities(city, regionid) VALUES('Ostashkov', 33);
INSERT INTO cities(city, regionid) VALUES('Rzhev', 33);
INSERT INTO cities(city, regionid) VALUES('Staritsa', 33);
INSERT INTO cities(city, regionid) VALUES('Toropets', 33);
INSERT INTO cities(city, regionid) VALUES('Torzhok', 33);
INSERT INTO cities(city, regionid) VALUES('Tver', 33);
INSERT INTO cities(city, regionid) VALUES('Udomlya', 33);
INSERT INTO cities(city, regionid) VALUES('Vesyegonsk', 33);
INSERT INTO cities(city, regionid) VALUES('Vyshny Volochyok', 33);
INSERT INTO cities(city, regionid) VALUES('Zapadnaya Dvina', 33);
INSERT INTO cities(city, regionid) VALUES('Zubtsov', 33);

INSERT INTO cities(city, regionid) VALUES('Barnaul', 34);
INSERT INTO cities(city, regionid) VALUES('Belokurikha', 34);
INSERT INTO cities(city, regionid) VALUES('Biysk', 34);
INSERT INTO cities(city, regionid) VALUES('Gornyak', 34);
INSERT INTO cities(city, regionid) VALUES('Kamen-na-Obi', 34);
INSERT INTO cities(city, regionid) VALUES('Novoaltaysk', 34);
INSERT INTO cities(city, regionid) VALUES('Rubtsovsk', 34);
INSERT INTO cities(city, regionid) VALUES('Slavgorod', 34);
INSERT INTO cities(city, regionid) VALUES('Yarovoye', 34);
INSERT INTO cities(city, regionid) VALUES('Zarinsk', 34);
INSERT INTO cities(city, regionid) VALUES('Zmeinogorsk', 34);

INSERT INTO cities(city, regionid) VALUES('Belyov', 35);
INSERT INTO cities(city, regionid) VALUES('Bogoroditsk', 35);
INSERT INTO cities(city, regionid) VALUES('Bolokhovo', 35);
INSERT INTO cities(city, regionid) VALUES('Chekalin', 35);
INSERT INTO cities(city, regionid) VALUES('Donskoy', 35);
INSERT INTO cities(city, regionid) VALUES('Kimovsk', 35);
INSERT INTO cities(city, regionid) VALUES('Kireyevsk', 35);
INSERT INTO cities(city, regionid) VALUES('Lipki', 35);
INSERT INTO cities(city, regionid) VALUES('Novomoskovsk', 35);
INSERT INTO cities(city, regionid) VALUES('Plavsk', 35);
INSERT INTO cities(city, regionid) VALUES('Shchyokino', 35);
INSERT INTO cities(city, regionid) VALUES('Sokolniki', 35);
INSERT INTO cities(city, regionid) VALUES('Sovetsk', 35);
INSERT INTO cities(city, regionid) VALUES('Suvorov', 35);
INSERT INTO cities(city, regionid) VALUES('Tula', 35);
INSERT INTO cities(city, regionid) VALUES('Uzlovaya', 35);
INSERT INTO cities(city, regionid) VALUES('Venyov', 35);
INSERT INTO cities(city, regionid) VALUES('Yasnogorsk', 35);
INSERT INTO cities(city, regionid) VALUES('Yefremov', 35);


INSERT INTO cities(city, regionid) VALUES('Vilyuchinsk', 37);
INSERT INTO cities(city, regionid) VALUES('Yelizovo', 37);

INSERT INTO cities(city, regionid) VALUES('Volzhsk', 38);
INSERT INTO cities(city, regionid) VALUES('Yoshkar-Ola', 38);
INSERT INTO cities(city, regionid) VALUES('Zvenigovo', 38);

INSERT INTO cities(city, regionid) VALUES('Susuman', 39);

INSERT INTO cities(city, regionid) VALUES('Buguruslan', 40);
INSERT INTO cities(city, regionid) VALUES('Buzuluk', 40);
INSERT INTO cities(city, regionid) VALUES('Gay', 40);
INSERT INTO cities(city, regionid) VALUES('Kuvandyk', 40);
INSERT INTO cities(city, regionid) VALUES('Mednogorsk', 40);
INSERT INTO cities(city, regionid) VALUES('Novotroitsk', 40);
INSERT INTO cities(city, regionid) VALUES('Orenburg', 40);
INSERT INTO cities(city, regionid) VALUES('Orsk', 40);
INSERT INTO cities(city, regionid) VALUES('Sol-Iletsk', 40);
INSERT INTO cities(city, regionid) VALUES('Sorochinsk', 40);
INSERT INTO cities(city, regionid) VALUES('Yasny', 40);

INSERT INTO cities(city, regionid) VALUES('Desnogorsk', 41);
INSERT INTO cities(city, regionid) VALUES('Dorogobuzh', 41);
INSERT INTO cities(city, regionid) VALUES('Dukhovshchina', 41);
INSERT INTO cities(city, regionid) VALUES('Gagarin', 41);
INSERT INTO cities(city, regionid) VALUES('Pochinok', 41);
INSERT INTO cities(city, regionid) VALUES('Roslavl', 41);
INSERT INTO cities(city, regionid) VALUES('Rudnya', 41);
INSERT INTO cities(city, regionid) VALUES('Safonovo', 41);
INSERT INTO cities(city, regionid) VALUES('Smolensk', 41);
INSERT INTO cities(city, regionid) VALUES('Sychyovka', 41);
INSERT INTO cities(city, regionid) VALUES('Velizh', 41);
INSERT INTO cities(city, regionid) VALUES('Vyazma', 41);
INSERT INTO cities(city, regionid) VALUES('Yartsevo', 41);
INSERT INTO cities(city, regionid) VALUES('Yelnya', 41);


INSERT INTO cities(city, regionid) VALUES('Izhevsk', 43);
INSERT INTO cities(city, regionid) VALUES('Kambarka', 43);
INSERT INTO cities(city, regionid) VALUES('Mozhga', 43);
INSERT INTO cities(city, regionid) VALUES('Sarapul', 43);
INSERT INTO cities(city, regionid) VALUES('Votkinsk', 43);

INSERT INTO cities(city, regionid) VALUES('Bikin', 44);
INSERT INTO cities(city, regionid) VALUES('Khabarovsk', 44);
INSERT INTO cities(city, regionid) VALUES('Komsomolsk-on-Amur', 44);
INSERT INTO cities(city, regionid) VALUES('Nikolayevsk-on-Amur', 44);
INSERT INTO cities(city, regionid) VALUES('Sovetskaya Gavan', 44);
INSERT INTO cities(city, regionid) VALUES('Vyazemsky', 44);

INSERT INTO cities(city, regionid) VALUES('Cheboksary', 45);
INSERT INTO cities(city, regionid) VALUES('Kanash', 45);
INSERT INTO cities(city, regionid) VALUES('Kozlovka', 45);
INSERT INTO cities(city, regionid) VALUES('Mariinsky Posad', 45);
INSERT INTO cities(city, regionid) VALUES('Novocheboksarsk', 45);
INSERT INTO cities(city, regionid) VALUES('Shumerlya', 45);
INSERT INTO cities(city, regionid) VALUES('Tsivilsk', 45);
INSERT INTO cities(city, regionid) VALUES('Yadrin', 45);

INSERT INTO cities(city, regionid) VALUES('Atkarsk', 46);
INSERT INTO cities(city, regionid) VALUES('Balakovo', 46);
INSERT INTO cities(city, regionid) VALUES('Balashov', 46);
INSERT INTO cities(city, regionid) VALUES('Engels', 46);
INSERT INTO cities(city, regionid) VALUES('Kalininsk', 46);
INSERT INTO cities(city, regionid) VALUES('Khvalynsk', 46);
INSERT INTO cities(city, regionid) VALUES('Krasnoarmeysk', 46);
INSERT INTO cities(city, regionid) VALUES('Krasny Kut', 46);
INSERT INTO cities(city, regionid) VALUES('Marks', 46);
INSERT INTO cities(city, regionid) VALUES('Novouzensk', 46);
INSERT INTO cities(city, regionid) VALUES('Petrovsk', 46);
INSERT INTO cities(city, regionid) VALUES('Pugachyov', 46);
INSERT INTO cities(city, regionid) VALUES('Rtishchevo', 46);
INSERT INTO cities(city, regionid) VALUES('Saratov', 46);
INSERT INTO cities(city, regionid) VALUES('Shikhany', 46);
INSERT INTO cities(city, regionid) VALUES('Volsk', 46);
INSERT INTO cities(city, regionid) VALUES('Yershov', 46);

INSERT INTO cities(city, regionid) VALUES('Dagestanskiye Ogni', 47);
INSERT INTO cities(city, regionid) VALUES('Derbent', 47);
INSERT INTO cities(city, regionid) VALUES('Izberbash', 47);
INSERT INTO cities(city, regionid) VALUES('Kaspiysk', 47);
INSERT INTO cities(city, regionid) VALUES('Khasavyurt', 47);
INSERT INTO cities(city, regionid) VALUES('Kizilyurt', 47);
INSERT INTO cities(city, regionid) VALUES('Kizlyar', 47);
INSERT INTO cities(city, regionid) VALUES('Makhachkala', 47);
INSERT INTO cities(city, regionid) VALUES('Yuzhno-Sukhokumsk', 47);

INSERT INTO cities(city, regionid) VALUES('Budyonnovsk', 48);
INSERT INTO cities(city, regionid) VALUES('Georgiyevsk', 48);
INSERT INTO cities(city, regionid) VALUES('Ipatovo', 48);
INSERT INTO cities(city, regionid) VALUES('Izobilny', 48);
INSERT INTO cities(city, regionid) VALUES('Kislovodsk', 48);
INSERT INTO cities(city, regionid) VALUES('Lermontov', 48);
INSERT INTO cities(city, regionid) VALUES('Mikhaylovsk', 48);
INSERT INTO cities(city, regionid) VALUES('Mineralnye Vody', 48);
INSERT INTO cities(city, regionid) VALUES('Neftekumsk', 48);
INSERT INTO cities(city, regionid) VALUES('Nevinnomyssk', 48);
INSERT INTO cities(city, regionid) VALUES('Novoalexandrovsk', 48);
INSERT INTO cities(city, regionid) VALUES('Novopavlovsk', 48);
INSERT INTO cities(city, regionid) VALUES('Pyatigorsk', 48);
INSERT INTO cities(city, regionid) VALUES('Stavropol', 48);
INSERT INTO cities(city, regionid) VALUES('Svetlograd', 48);
INSERT INTO cities(city, regionid) VALUES('Yessentuki', 48);
INSERT INTO cities(city, regionid) VALUES('Zelenokumsk', 48);
INSERT INTO cities(city, regionid) VALUES('Zheleznovodsk', 48);

INSERT INTO cities(city, regionid) VALUES('Kirov', 49);
INSERT INTO cities(city, regionid) VALUES('Kirovo-Chepetsk', 49);
INSERT INTO cities(city, regionid) VALUES('Kirs', 49);
INSERT INTO cities(city, regionid) VALUES('Kotelnich', 49);
INSERT INTO cities(city, regionid) VALUES('Luza', 49);
INSERT INTO cities(city, regionid) VALUES('Malmyzh', 49);
INSERT INTO cities(city, regionid) VALUES('Murashi', 49);
INSERT INTO cities(city, regionid) VALUES('Nolinsk', 49);
INSERT INTO cities(city, regionid) VALUES('Omutninsk', 49);
INSERT INTO cities(city, regionid) VALUES('Orlov', 49);
INSERT INTO cities(city, regionid) VALUES('Slobodskoy', 49);
INSERT INTO cities(city, regionid) VALUES('Sosnovka', 49);
INSERT INTO cities(city, regionid) VALUES('Sovetsk', 49);
INSERT INTO cities(city, regionid) VALUES('Urzhum', 49);
INSERT INTO cities(city, regionid) VALUES('Vyatskiye Polyany', 49);
INSERT INTO cities(city, regionid) VALUES('Yaransk', 49);
INSERT INTO cities(city, regionid) VALUES('Zuyevka', 49);

INSERT INTO cities(city, regionid) VALUES('Kataysk', 50);
INSERT INTO cities(city, regionid) VALUES('Kurgan', 50);
INSERT INTO cities(city, regionid) VALUES('Kurtamysh', 50);
INSERT INTO cities(city, regionid) VALUES('Makushino', 50);
INSERT INTO cities(city, regionid) VALUES('Petukhovo', 50);
INSERT INTO cities(city, regionid) VALUES('Shadrinsk', 50);
INSERT INTO cities(city, regionid) VALUES('Shchuchye', 50);
INSERT INTO cities(city, regionid) VALUES('Shumikha', 50);

INSERT INTO cities(city, regionid) VALUES('Belozersk', 51);
INSERT INTO cities(city, regionid) VALUES('Cherepovets', 51);
INSERT INTO cities(city, regionid) VALUES('Gryazovets', 51);
INSERT INTO cities(city, regionid) VALUES('Kadnikov', 51);
INSERT INTO cities(city, regionid) VALUES('Kharovsk', 51);
INSERT INTO cities(city, regionid) VALUES('Kirillov', 51);
INSERT INTO cities(city, regionid) VALUES('Krasavino', 51);
INSERT INTO cities(city, regionid) VALUES('Nikolsk', 51);
INSERT INTO cities(city, regionid) VALUES('Sokol', 51);
INSERT INTO cities(city, regionid) VALUES('Totma', 51);
INSERT INTO cities(city, regionid) VALUES('Ustyuzhna', 51);
INSERT INTO cities(city, regionid) VALUES('Veliky Ustyug', 51);
INSERT INTO cities(city, regionid) VALUES('Vologda', 51);
INSERT INTO cities(city, regionid) VALUES('Vytegra', 51);

INSERT INTO cities(city, regionid) VALUES('Aramil', 52);
INSERT INTO cities(city, regionid) VALUES('Artyomovsky', 52);
INSERT INTO cities(city, regionid) VALUES('Asbest', 52);
INSERT INTO cities(city, regionid) VALUES('Berezovsky', 52);
INSERT INTO cities(city, regionid) VALUES('Bogdanovich', 52);
INSERT INTO cities(city, regionid) VALUES('Degtyarsk', 52);
INSERT INTO cities(city, regionid) VALUES('Irbit', 52);
INSERT INTO cities(city, regionid) VALUES('Ivdel', 52);
INSERT INTO cities(city, regionid) VALUES('Kachkanar', 52);
INSERT INTO cities(city, regionid) VALUES('Kamensk-Uralsky', 52);
INSERT INTO cities(city, regionid) VALUES('Kamyshlov', 52);
INSERT INTO cities(city, regionid) VALUES('Karpinsk', 52);
INSERT INTO cities(city, regionid) VALUES('Kirovgrad', 52);
INSERT INTO cities(city, regionid) VALUES('Krasnoturyinsk', 52);
INSERT INTO cities(city, regionid) VALUES('Krasnoufimsk', 52);
INSERT INTO cities(city, regionid) VALUES('Krasnouralsk', 52);
INSERT INTO cities(city, regionid) VALUES('Kushva', 52);
INSERT INTO cities(city, regionid) VALUES('Lesnoy', 52);
INSERT INTO cities(city, regionid) VALUES('Mikhaylovsk', 52);
INSERT INTO cities(city, regionid) VALUES('Nevyansk', 52);
INSERT INTO cities(city, regionid) VALUES('Nizhniye Sergi', 52);
INSERT INTO cities(city, regionid) VALUES('Nizhny Tagil', 52);
INSERT INTO cities(city, regionid) VALUES('Nizhnyaya Salda', 52);
INSERT INTO cities(city, regionid) VALUES('Nizhnyaya Tura', 52);
INSERT INTO cities(city, regionid) VALUES('Novaya Lyalya', 52);
INSERT INTO cities(city, regionid) VALUES('Novouralsk', 52);
INSERT INTO cities(city, regionid) VALUES('Pervouralsk', 52);
INSERT INTO cities(city, regionid) VALUES('Polevskoy', 52);
INSERT INTO cities(city, regionid) VALUES('Revda', 52);
INSERT INTO cities(city, regionid) VALUES('Rezh', 52);
INSERT INTO cities(city, regionid) VALUES('Serov', 52);
INSERT INTO cities(city, regionid) VALUES('Severouralsk', 52);
INSERT INTO cities(city, regionid) VALUES('Sredneuralsk', 52);
INSERT INTO cities(city, regionid) VALUES('Sukhoy Log', 52);
INSERT INTO cities(city, regionid) VALUES('Sysert', 52);
INSERT INTO cities(city, regionid) VALUES('Talitsa', 52);
INSERT INTO cities(city, regionid) VALUES('Tavda', 52);
INSERT INTO cities(city, regionid) VALUES('Turinsk', 52);
INSERT INTO cities(city, regionid) VALUES('Verkhny Tagil', 52);
INSERT INTO cities(city, regionid) VALUES('Verkhnyaya Pyshma', 52);
INSERT INTO cities(city, regionid) VALUES('Verkhnyaya Salda', 52);
INSERT INTO cities(city, regionid) VALUES('Verkhnyaya Tura', 52);
INSERT INTO cities(city, regionid) VALUES('Verkhoturye', 52);
INSERT INTO cities(city, regionid) VALUES('Volchansk', 52);
INSERT INTO cities(city, regionid) VALUES('Yekaterinburg', 52);
INSERT INTO cities(city, regionid) VALUES('Zarechny', 52);

INSERT INTO cities(city, regionid) VALUES('Gadzhiyevo', 53);
INSERT INTO cities(city, regionid) VALUES('Kandalaksha', 53);
INSERT INTO cities(city, regionid) VALUES('Kirovsk', 53);
INSERT INTO cities(city, regionid) VALUES('Kola', 53);
INSERT INTO cities(city, regionid) VALUES('Kovdor', 53);
INSERT INTO cities(city, regionid) VALUES('Monchegorsk', 53);
INSERT INTO cities(city, regionid) VALUES('Murmansk', 53);
INSERT INTO cities(city, regionid) VALUES('Olenegorsk', 53);
INSERT INTO cities(city, regionid) VALUES('Ostrovnoy', 53);
INSERT INTO cities(city, regionid) VALUES('Polyarny', 53);
INSERT INTO cities(city, regionid) VALUES('Polyarnye Zori', 53);
INSERT INTO cities(city, regionid) VALUES('Severomorsk', 53);
INSERT INTO cities(city, regionid) VALUES('Snezhnogorsk', 53);
INSERT INTO cities(city, regionid) VALUES('Zaozyorsk', 53);
INSERT INTO cities(city, regionid) VALUES('Zapolyarny', 53);

INSERT INTO cities(city, regionid) VALUES('Gavrilov Posad', 54);
INSERT INTO cities(city, regionid) VALUES('Ivanovo', 54);
INSERT INTO cities(city, regionid) VALUES('Kineshma', 54);
INSERT INTO cities(city, regionid) VALUES('Kokhma', 54);
INSERT INTO cities(city, regionid) VALUES('Komsomolsk', 54);
INSERT INTO cities(city, regionid) VALUES('Navoloki', 54);
INSERT INTO cities(city, regionid) VALUES('Plyos', 54);
INSERT INTO cities(city, regionid) VALUES('Privolzhsk', 54);
INSERT INTO cities(city, regionid) VALUES('Puchezh', 54);
INSERT INTO cities(city, regionid) VALUES('Rodniki', 54);
INSERT INTO cities(city, regionid) VALUES('Shuya', 54);
INSERT INTO cities(city, regionid) VALUES('Teykovo', 54);
INSERT INTO cities(city, regionid) VALUES('Vichuga', 54);
INSERT INTO cities(city, regionid) VALUES('Yuryevets', 54);
INSERT INTO cities(city, regionid) VALUES('Yuzha', 54);
INSERT INTO cities(city, regionid) VALUES('Zavolzhsk', 54);

INSERT INTO cities(city, regionid) VALUES('Gusinoozyorsk', 55);
INSERT INTO cities(city, regionid) VALUES('Kyakhta', 55);
INSERT INTO cities(city, regionid) VALUES('Severobaykalsk', 55);
INSERT INTO cities(city, regionid) VALUES('Ulan-Ude', 55);
INSERT INTO cities(city, regionid) VALUES('Zakamensk', 55);

INSERT INTO cities(city, regionid) VALUES('Mikun', 56);
INSERT INTO cities(city, regionid) VALUES('Pechora', 56);
INSERT INTO cities(city, regionid) VALUES('Sosnogorsk', 56);
INSERT INTO cities(city, regionid) VALUES('Syktyvkar', 56);
INSERT INTO cities(city, regionid) VALUES('Ukhta', 56);
INSERT INTO cities(city, regionid) VALUES('Usinsk', 56);
INSERT INTO cities(city, regionid) VALUES('Vorkuta', 56);
INSERT INTO cities(city, regionid) VALUES('Vuktyl', 56);
INSERT INTO cities(city, regionid) VALUES('Yemva', 56);

INSERT INTO cities(city, regionid) VALUES('Anapa', 57);
INSERT INTO cities(city, regionid) VALUES('Apsheronsk', 57);
INSERT INTO cities(city, regionid) VALUES('Armavir', 57);
INSERT INTO cities(city, regionid) VALUES('Belorechensk', 57);
INSERT INTO cities(city, regionid) VALUES('Gelendzhik', 57);
INSERT INTO cities(city, regionid) VALUES('Goryachy Klyuch', 57);
INSERT INTO cities(city, regionid) VALUES('Gulkevichi', 57);
INSERT INTO cities(city, regionid) VALUES('Khadyzhensk', 57);
INSERT INTO cities(city, regionid) VALUES('Korenovsk', 57);
INSERT INTO cities(city, regionid) VALUES('Krasnodar', 57);
INSERT INTO cities(city, regionid) VALUES('Kropotkin', 57);
INSERT INTO cities(city, regionid) VALUES('Krymsk', 57);
INSERT INTO cities(city, regionid) VALUES('Kurganinsk', 57);
INSERT INTO cities(city, regionid) VALUES('Labinsk', 57);
INSERT INTO cities(city, regionid) VALUES('Novokubansk', 57);
INSERT INTO cities(city, regionid) VALUES('Novorossiysk', 57);
INSERT INTO cities(city, regionid) VALUES('Primorsko-Akhtarsk', 57);
INSERT INTO cities(city, regionid) VALUES('Slavyansk-na-Kubani', 57);
INSERT INTO cities(city, regionid) VALUES('Sochi', 57);
INSERT INTO cities(city, regionid) VALUES('Temryuk', 57);
INSERT INTO cities(city, regionid) VALUES('Tikhoretsk', 57);
INSERT INTO cities(city, regionid) VALUES('Timashyovsk', 57);
INSERT INTO cities(city, regionid) VALUES('Tuapse', 57);
INSERT INTO cities(city, regionid) VALUES('Ust-Labinsk', 57);
INSERT INTO cities(city, regionid) VALUES('Yeysk', 57);

INSERT INTO cities(city, regionid) VALUES('Dyatkovo', 58);
INSERT INTO cities(city, regionid) VALUES('Fokino', 58);
INSERT INTO cities(city, regionid) VALUES('Karachev', 58);
INSERT INTO cities(city, regionid) VALUES('Klintsy', 58);
INSERT INTO cities(city, regionid) VALUES('Mglin', 58);
INSERT INTO cities(city, regionid) VALUES('Novozybkov', 58);
INSERT INTO cities(city, regionid) VALUES('Pochep', 58);
INSERT INTO cities(city, regionid) VALUES('Seltso', 58);
INSERT INTO cities(city, regionid) VALUES('Sevsk', 58);
INSERT INTO cities(city, regionid) VALUES('Starodub', 58);
INSERT INTO cities(city, regionid) VALUES('Surazh', 58);
INSERT INTO cities(city, regionid) VALUES('Trubchevsk', 58);
INSERT INTO cities(city, regionid) VALUES('Unecha', 58);
INSERT INTO cities(city, regionid) VALUES('Zhukovka', 58);
INSERT INTO cities(city, regionid) VALUES('Zlynka', 58);

INSERT INTO cities(city, regionid) VALUES('Bilibino', 59);
INSERT INTO cities(city, regionid) VALUES('Pevek', 59);

INSERT INTO cities(city, regionid) VALUES('Balashikha', 60);
INSERT INTO cities(city, regionid) VALUES('Bronnitsy', 60);
INSERT INTO cities(city, regionid) VALUES('Chekhov', 60);
INSERT INTO cities(city, regionid) VALUES('Chernogolovka', 60);
INSERT INTO cities(city, regionid) VALUES('Dedovsk', 60);
INSERT INTO cities(city, regionid) VALUES('Dmitrov', 60);
INSERT INTO cities(city, regionid) VALUES('Dolgoprudny', 60);
INSERT INTO cities(city, regionid) VALUES('Domodedovo', 60);
INSERT INTO cities(city, regionid) VALUES('Drezna', 60);
INSERT INTO cities(city, regionid) VALUES('Dubna', 60);
INSERT INTO cities(city, regionid) VALUES('Dzerzhinsky', 60);
INSERT INTO cities(city, regionid) VALUES('Elektrogorsk', 60);
INSERT INTO cities(city, regionid) VALUES('Elektrostal', 60);
INSERT INTO cities(city, regionid) VALUES('Elektrougli', 60);
INSERT INTO cities(city, regionid) VALUES('Fryazino', 60);
INSERT INTO cities(city, regionid) VALUES('Golitsyno', 60);
INSERT INTO cities(city, regionid) VALUES('Istra', 60);
INSERT INTO cities(city, regionid) VALUES('Ivanteyevka', 60);
INSERT INTO cities(city, regionid) VALUES('Kashira', 60);
INSERT INTO cities(city, regionid) VALUES('Khimki', 60);
INSERT INTO cities(city, regionid) VALUES('Khotkovo', 60);
INSERT INTO cities(city, regionid) VALUES('Klimovsk', 60);
INSERT INTO cities(city, regionid) VALUES('Klin', 60);
INSERT INTO cities(city, regionid) VALUES('Kolomna', 60);
INSERT INTO cities(city, regionid) VALUES('Korolyov', 60);
INSERT INTO cities(city, regionid) VALUES('Kotelniki', 60);
INSERT INTO cities(city, regionid) VALUES('Krasnoarmeysk', 60);
INSERT INTO cities(city, regionid) VALUES('Krasnogorsk', 60);
INSERT INTO cities(city, regionid) VALUES('Krasnozavodsk', 60);
INSERT INTO cities(city, regionid) VALUES('Krasnoznamensk', 60);
INSERT INTO cities(city, regionid) VALUES('Kubinka', 60);
INSERT INTO cities(city, regionid) VALUES('Kurovskoye', 60);
INSERT INTO cities(city, regionid) VALUES('Likino-Dulyovo', 60);
INSERT INTO cities(city, regionid) VALUES('Lobnya', 60);
INSERT INTO cities(city, regionid) VALUES('Losino-Petrovsky', 60);
INSERT INTO cities(city, regionid) VALUES('Lukhovitsy', 60);
INSERT INTO cities(city, regionid) VALUES('Lytkarino', 60);
INSERT INTO cities(city, regionid) VALUES('Lyubertsy', 60);
INSERT INTO cities(city, regionid) VALUES('Mozhaysk', 60);
INSERT INTO cities(city, regionid) VALUES('Mytishchi', 60);
INSERT INTO cities(city, regionid) VALUES('Naro-Fominsk', 60);
INSERT INTO cities(city, regionid) VALUES('Noginsk', 60);
INSERT INTO cities(city, regionid) VALUES('Odintsovo', 60);
INSERT INTO cities(city, regionid) VALUES('Orekhovo-Zuyevo', 60);
INSERT INTO cities(city, regionid) VALUES('Ozherelye', 60);
INSERT INTO cities(city, regionid) VALUES('Ozyory', 60);
INSERT INTO cities(city, regionid) VALUES('Pavlovsky Posad', 60);
INSERT INTO cities(city, regionid) VALUES('Peresvet', 60);
INSERT INTO cities(city, regionid) VALUES('Podolsk', 60);
INSERT INTO cities(city, regionid) VALUES('Protvino', 60);
INSERT INTO cities(city, regionid) VALUES('Pushchino', 60);
INSERT INTO cities(city, regionid) VALUES('Pushkino', 60);
INSERT INTO cities(city, regionid) VALUES('Ramenskoye', 60);
INSERT INTO cities(city, regionid) VALUES('Reutov', 60);
INSERT INTO cities(city, regionid) VALUES('Roshal', 60);
INSERT INTO cities(city, regionid) VALUES('Ruza', 60);
INSERT INTO cities(city, regionid) VALUES('Sergiyev Posad', 60);
INSERT INTO cities(city, regionid) VALUES('Serpukhov', 60);
INSERT INTO cities(city, regionid) VALUES('Shatura', 60);
INSERT INTO cities(city, regionid) VALUES('Shcherbinka', 60);
INSERT INTO cities(city, regionid) VALUES('Shchyolkovo', 60);
INSERT INTO cities(city, regionid) VALUES('Solnechnogorsk', 60);
INSERT INTO cities(city, regionid) VALUES('Staraya Kupavna', 60);
INSERT INTO cities(city, regionid) VALUES('Stupino', 60);
INSERT INTO cities(city, regionid) VALUES('Taldom', 60);
INSERT INTO cities(city, regionid) VALUES('Vereya', 60);
INSERT INTO cities(city, regionid) VALUES('Vidnoye', 60);
INSERT INTO cities(city, regionid) VALUES('Volokolamsk', 60);
INSERT INTO cities(city, regionid) VALUES('Voskresensk', 60);
INSERT INTO cities(city, regionid) VALUES('Vysokovsk', 60);
INSERT INTO cities(city, regionid) VALUES('Yakhroma', 60);
INSERT INTO cities(city, regionid) VALUES('Yegoryevsk', 60);
INSERT INTO cities(city, regionid) VALUES('Yubileyny', 60);
INSERT INTO cities(city, regionid) VALUES('Zaraysk', 60);
INSERT INTO cities(city, regionid) VALUES('Zheleznodorozhny', 60);
INSERT INTO cities(city, regionid) VALUES('Zhukovsky', 60);
INSERT INTO cities(city, regionid) VALUES('Zvenigorod', 60);

INSERT INTO cities(city, regionid) VALUES('Gavrilov-Yam', 61);
INSERT INTO cities(city, regionid) VALUES('Lyubim', 61);
INSERT INTO cities(city, regionid) VALUES('Myshkin', 61);
INSERT INTO cities(city, regionid) VALUES('Pereslavl-Zalessky', 61);
INSERT INTO cities(city, regionid) VALUES('Poshekhonye', 61);
INSERT INTO cities(city, regionid) VALUES('Rostov', 61);
INSERT INTO cities(city, regionid) VALUES('Rybinsk', 61);
INSERT INTO cities(city, regionid) VALUES('Tutayev', 61);
INSERT INTO cities(city, regionid) VALUES('Uglich', 61);
INSERT INTO cities(city, regionid) VALUES('Yaroslavl', 61);

INSERT INTO cities(city, regionid) VALUES('Kinel', 62);
INSERT INTO cities(city, regionid) VALUES('Neftegorsk, Samara Oblast', 62);
INSERT INTO cities(city, regionid) VALUES('Novokuybyshevsk', 62);
INSERT INTO cities(city, regionid) VALUES('Oktyabrsk', 62);
INSERT INTO cities(city, regionid) VALUES('Otradny', 62);
INSERT INTO cities(city, regionid) VALUES('Pokhvistnevo', 62);
INSERT INTO cities(city, regionid) VALUES('Samara', 62);
INSERT INTO cities(city, regionid) VALUES('Syzran', 62);
INSERT INTO cities(city, regionid) VALUES('Tolyatti', 62);
INSERT INTO cities(city, regionid) VALUES('Zhigulyovsk', 62);

INSERT INTO cities(city, regionid) VALUES('Almetyevsk', 63);
INSERT INTO cities(city, regionid) VALUES('Aznakayevo', 63);
INSERT INTO cities(city, regionid) VALUES('Bavly', 63);
INSERT INTO cities(city, regionid) VALUES('Bolgar', 63);
INSERT INTO cities(city, regionid) VALUES('Bugulma', 63);
INSERT INTO cities(city, regionid) VALUES('Buinsk', 63);
INSERT INTO cities(city, regionid) VALUES('Chistopol', 63);
INSERT INTO cities(city, regionid) VALUES('Innopolis', 63);
INSERT INTO cities(city, regionid) VALUES('Kazan', 63);
INSERT INTO cities(city, regionid) VALUES('Laishevo', 63);
INSERT INTO cities(city, regionid) VALUES('Leninogorsk', 63);
INSERT INTO cities(city, regionid) VALUES('Mamadysh', 63);
INSERT INTO cities(city, regionid) VALUES('Mendeleyevsk', 63);
INSERT INTO cities(city, regionid) VALUES('Menzelinsk', 63);
INSERT INTO cities(city, regionid) VALUES('Naberezhnye Chelny', 63);
INSERT INTO cities(city, regionid) VALUES('Nizhnekamsk', 63);
INSERT INTO cities(city, regionid) VALUES('Nurlat', 63);
INSERT INTO cities(city, regionid) VALUES('Tetyushi', 63);
INSERT INTO cities(city, regionid) VALUES('Yelabuga', 63);
INSERT INTO cities(city, regionid) VALUES('Zainsk', 63);
INSERT INTO cities(city, regionid) VALUES('Zelenodolsk', 63);

INSERT INTO cities(city, regionid) VALUES('Gorodishche', 64);
INSERT INTO cities(city, regionid) VALUES('Kamenka', 64);
INSERT INTO cities(city, regionid) VALUES('Kuznetsk', 64);
INSERT INTO cities(city, regionid) VALUES('Nikolsk', 64);
INSERT INTO cities(city, regionid) VALUES('Nizhny Lomov', 64);
INSERT INTO cities(city, regionid) VALUES('Penza', 64);
INSERT INTO cities(city, regionid) VALUES('Serdobsk', 64);
INSERT INTO cities(city, regionid) VALUES('Spassk', 64);
INSERT INTO cities(city, regionid) VALUES('Sursk', 64);
INSERT INTO cities(city, regionid) VALUES('Zarechny', 64);

INSERT INTO cities(city, regionid) VALUES('Korablino', 65);
INSERT INTO cities(city, regionid) VALUES('Mikhaylov', 65);
INSERT INTO cities(city, regionid) VALUES('Novomichurinsk', 65);
INSERT INTO cities(city, regionid) VALUES('Ryazan', 65);
INSERT INTO cities(city, regionid) VALUES('Ryazhsk', 65);
INSERT INTO cities(city, regionid) VALUES('Rybnoye', 65);
INSERT INTO cities(city, regionid) VALUES('Sasovo', 65);
INSERT INTO cities(city, regionid) VALUES('Shatsk', 65);
INSERT INTO cities(city, regionid) VALUES('Skopin', 65);
INSERT INTO cities(city, regionid) VALUES('Spas-Klepiki', 65);
INSERT INTO cities(city, regionid) VALUES('Spassk-Ryazansky', 65);

INSERT INTO cities(city, regionid) VALUES('Insar', 66);
INSERT INTO cities(city, regionid) VALUES('Kovylkino', 66);
INSERT INTO cities(city, regionid) VALUES('Krasnoslobodsk', 66);
INSERT INTO cities(city, regionid) VALUES('Ruzayevka', 66);
INSERT INTO cities(city, regionid) VALUES('Saransk', 66);
INSERT INTO cities(city, regionid) VALUES('Temnikov', 66);

INSERT INTO cities(city, regionid) VALUES('Berezniki', 67);
INSERT INTO cities(city, regionid) VALUES('Chaykovsky', 67);
INSERT INTO cities(city, regionid) VALUES('Cherdyn', 67);
INSERT INTO cities(city, regionid) VALUES('Chernushka', 67);
INSERT INTO cities(city, regionid) VALUES('Chusovoy', 67);
INSERT INTO cities(city, regionid) VALUES('Chyormoz', 67);
INSERT INTO cities(city, regionid) VALUES('Dobryanka', 67);
INSERT INTO cities(city, regionid) VALUES('Gornozavodsk', 67);
INSERT INTO cities(city, regionid) VALUES('Gremyachinsk', 67);
INSERT INTO cities(city, regionid) VALUES('Gubakha', 67);
INSERT INTO cities(city, regionid) VALUES('Kizel', 67);
INSERT INTO cities(city, regionid) VALUES('Krasnokamsk', 67);
INSERT INTO cities(city, regionid) VALUES('Krasnovishersk', 67);
INSERT INTO cities(city, regionid) VALUES('Kudymkar', 67);
INSERT INTO cities(city, regionid) VALUES('Kungur', 67);
INSERT INTO cities(city, regionid) VALUES('Lysva', 67);
INSERT INTO cities(city, regionid) VALUES('Nytva', 67);
INSERT INTO cities(city, regionid) VALUES('Ochyor', 67);
INSERT INTO cities(city, regionid) VALUES('Okhansk', 67);
INSERT INTO cities(city, regionid) VALUES('Osa', 67);
INSERT INTO cities(city, regionid) VALUES('Perm', 67);
INSERT INTO cities(city, regionid) VALUES('Solikamsk', 67);
INSERT INTO cities(city, regionid) VALUES('Usolye', 67);
INSERT INTO cities(city, regionid) VALUES('Vereshchagino', 67);

INSERT INTO cities(city, regionid) VALUES('Dankov', 68);
INSERT INTO cities(city, regionid) VALUES('Gryazi', 68);
INSERT INTO cities(city, regionid) VALUES('Lebedyan', 68);
INSERT INTO cities(city, regionid) VALUES('Lipetsk', 68);
INSERT INTO cities(city, regionid) VALUES('Usman', 68);
INSERT INTO cities(city, regionid) VALUES('Yelets', 68);
INSERT INTO cities(city, regionid) VALUES('Zadonsk', 68);

INSERT INTO cities(city, regionid) VALUES('Abaza', 69);
INSERT INTO cities(city, regionid) VALUES('Chernogorsk', 69);
INSERT INTO cities(city, regionid) VALUES('Sayanogorsk', 69);
INSERT INTO cities(city, regionid) VALUES('Sorsk', 69);

INSERT INTO cities(city, regionid) VALUES('Blagoveshchensk', 70);
INSERT INTO cities(city, regionid) VALUES('Raychikhinsk', 70);
INSERT INTO cities(city, regionid) VALUES('Shimanovsk', 70);
INSERT INTO cities(city, regionid) VALUES('Skovorodino', 70);
INSERT INTO cities(city, regionid) VALUES('Svobodny', 70);
INSERT INTO cities(city, regionid) VALUES('Tynda', 70);
INSERT INTO cities(city, regionid) VALUES('Zavitinsk', 70);
INSERT INTO cities(city, regionid) VALUES('Zeya', 70);

INSERT INTO cities(city, regionid) VALUES('Magas', 71);
INSERT INTO cities(city, regionid) VALUES('Malgobek', 71);
INSERT INTO cities(city, regionid) VALUES('Nazran', 71);

INSERT INTO cities(city, regionid) VALUES('Boguchar', 72);
INSERT INTO cities(city, regionid) VALUES('Borisoglebsk', 72);
INSERT INTO cities(city, regionid) VALUES('Buturlinovka', 72);
INSERT INTO cities(city, regionid) VALUES('Ertil', 72);
INSERT INTO cities(city, regionid) VALUES('Kalach', 72);
INSERT INTO cities(city, regionid) VALUES('Liski', 72);
INSERT INTO cities(city, regionid) VALUES('Novokhopyorsk', 72);
INSERT INTO cities(city, regionid) VALUES('Novovoronezh', 72);
INSERT INTO cities(city, regionid) VALUES('Ostrogozhsk', 72);
INSERT INTO cities(city, regionid) VALUES('Pavlovsk', 72);
INSERT INTO cities(city, regionid) VALUES('Povorino', 72);
INSERT INTO cities(city, regionid) VALUES('Rossosh', 72);
INSERT INTO cities(city, regionid) VALUES('Semiluki', 72);
INSERT INTO cities(city, regionid) VALUES('Voronezh', 72);

INSERT INTO cities(city, regionid) VALUES('Grozny', 73);
INSERT INTO cities(city, regionid) VALUES('Gudermes', 73);
INSERT INTO cities(city, regionid) VALUES('Shali', 73);
INSERT INTO cities(city, regionid) VALUES('Urus-Martan', 73);

INSERT INTO cities(city, regionid) VALUES('Chukhloma', 74);
INSERT INTO cities(city, regionid) VALUES('Galich', 74);
INSERT INTO cities(city, regionid) VALUES('Kologriv', 74);
INSERT INTO cities(city, regionid) VALUES('Kostroma', 74);
INSERT INTO cities(city, regionid) VALUES('Makaryev', 74);
INSERT INTO cities(city, regionid) VALUES('Manturovo', 74);
INSERT INTO cities(city, regionid) VALUES('Nerekhta', 74);
INSERT INTO cities(city, regionid) VALUES('Neya', 74);
INSERT INTO cities(city, regionid) VALUES('Sharya', 74);
INSERT INTO cities(city, regionid) VALUES('Soligalich', 74);
INSERT INTO cities(city, regionid) VALUES('Volgorechensk', 74);

INSERT INTO cities(city, regionid) VALUES('Gdov', 75);
INSERT INTO cities(city, regionid) VALUES('Nevel', 75);
INSERT INTO cities(city, regionid) VALUES('Novorzhev', 75);
INSERT INTO cities(city, regionid) VALUES('Novosokolniki', 75);
INSERT INTO cities(city, regionid) VALUES('Opochka', 75);
INSERT INTO cities(city, regionid) VALUES('Ostrov', 75);
INSERT INTO cities(city, regionid) VALUES('Pechory', 75);
INSERT INTO cities(city, regionid) VALUES('Porkhov', 75);
INSERT INTO cities(city, regionid) VALUES('Pskov', 75);
INSERT INTO cities(city, regionid) VALUES('Pustoshka', 75);
INSERT INTO cities(city, regionid) VALUES('Pytalovo', 75);
INSERT INTO cities(city, regionid) VALUES('Sebezh', 75);
INSERT INTO cities(city, regionid) VALUES('Velikiye Luki', 75);

INSERT INTO cities(city, regionid) VALUES('Artyom', 76);
INSERT INTO cities(city, regionid) VALUES('Bolshoy Kamen', 76);
INSERT INTO cities(city, regionid) VALUES('Dalnegorsk', 76);
INSERT INTO cities(city, regionid) VALUES('Dalnerechensk', 76);
INSERT INTO cities(city, regionid) VALUES('Fokino', 76);
INSERT INTO cities(city, regionid) VALUES('Lesozavodsk', 76);
INSERT INTO cities(city, regionid) VALUES('Nakhodka', 76);
INSERT INTO cities(city, regionid) VALUES('Partizansk', 76);
INSERT INTO cities(city, regionid) VALUES('Spassk-Dalny', 76);
INSERT INTO cities(city, regionid) VALUES('Ussuriysk', 76);
INSERT INTO cities(city, regionid) VALUES('Vladivostok', 76);

INSERT INTO cities(city, regionid) VALUES('Angarsk', 77);
INSERT INTO cities(city, regionid) VALUES('Baykalsk', 77);
INSERT INTO cities(city, regionid) VALUES('Biryusinsk', 77);
INSERT INTO cities(city, regionid) VALUES('Bodaybo', 77);
INSERT INTO cities(city, regionid) VALUES('Bratsk', 77);
INSERT INTO cities(city, regionid) VALUES('Cheremkhovo', 77);
INSERT INTO cities(city, regionid) VALUES('Irkutsk', 77);
INSERT INTO cities(city, regionid) VALUES('Kirensk', 77);
INSERT INTO cities(city, regionid) VALUES('Nizhneudinsk', 77);
INSERT INTO cities(city, regionid) VALUES('Sayansk', 77);
INSERT INTO cities(city, regionid) VALUES('Shelekhov', 77);
INSERT INTO cities(city, regionid) VALUES('Slyudyanka', 77);
INSERT INTO cities(city, regionid) VALUES('Svirsk', 77);
INSERT INTO cities(city, regionid) VALUES('Tayshet', 77);
INSERT INTO cities(city, regionid) VALUES('Tulun', 77);
INSERT INTO cities(city, regionid) VALUES('Usolye-Sibirskoye', 77);
INSERT INTO cities(city, regionid) VALUES('Ust-Ilimsk', 77);
INSERT INTO cities(city, regionid) VALUES('Ust-Kut', 77);
INSERT INTO cities(city, regionid) VALUES('Vikhorevka', 77);
INSERT INTO cities(city, regionid) VALUES('Zheleznogorsk-Ilimsky', 77);
INSERT INTO cities(city, regionid) VALUES('Zima', 77);

INSERT INTO cities(city, regionid) VALUES('Kotovsk', 78);
INSERT INTO cities(city, regionid) VALUES('Michurinsk', 78);
INSERT INTO cities(city, regionid) VALUES('Morshansk', 78);
INSERT INTO cities(city, regionid) VALUES('Rasskazovo', 78);
INSERT INTO cities(city, regionid) VALUES('Tambov', 78);
INSERT INTO cities(city, regionid) VALUES('Uvarovo', 78);
INSERT INTO cities(city, regionid) VALUES('Zherdevka', 78);

INSERT INTO cities(city, regionid) VALUES('Belovo', 79);
INSERT INTO cities(city, regionid) VALUES('Berezovsky', 79);
INSERT INTO cities(city, regionid) VALUES('Guryevsk', 79);
INSERT INTO cities(city, regionid) VALUES('Kaltan', 79);
INSERT INTO cities(city, regionid) VALUES('Kemerovo', 79);
INSERT INTO cities(city, regionid) VALUES('Kiselyovsk', 79);
INSERT INTO cities(city, regionid) VALUES('Leninsk-Kuznetsky', 79);
INSERT INTO cities(city, regionid) VALUES('Mariinsk', 79);
INSERT INTO cities(city, regionid) VALUES('Mezhdurechensk', 79);
INSERT INTO cities(city, regionid) VALUES('Myski', 79);
INSERT INTO cities(city, regionid) VALUES('Novokuznetsk', 79);
INSERT INTO cities(city, regionid) VALUES('Osinniki', 79);
INSERT INTO cities(city, regionid) VALUES('Polysayevo', 79);
INSERT INTO cities(city, regionid) VALUES('Prokopyevsk', 79);
INSERT INTO cities(city, regionid) VALUES('Salair', 79);
INSERT INTO cities(city, regionid) VALUES('Tashtagol', 79);
INSERT INTO cities(city, regionid) VALUES('Tayga', 79);
INSERT INTO cities(city, regionid) VALUES('Topki', 79);
INSERT INTO cities(city, regionid) VALUES('Yurga', 79);

INSERT INTO cities(city, regionid) VALUES('Chegem', 80);
INSERT INTO cities(city, regionid) VALUES('Maysky', 80);
INSERT INTO cities(city, regionid) VALUES('Nalchik', 80);
INSERT INTO cities(city, regionid) VALUES('Nartkala', 80);
INSERT INTO cities(city, regionid) VALUES('Prokhladny', 80);
INSERT INTO cities(city, regionid) VALUES('Terek', 80);
INSERT INTO cities(city, regionid) VALUES('Tyrnyauz', 80);

INSERT INTO cities(city, regionid) VALUES('Dimitrovgrad', 81);
INSERT INTO cities(city, regionid) VALUES('Inza', 81);
INSERT INTO cities(city, regionid) VALUES('Novoulyanovsk', 81);
INSERT INTO cities(city, regionid) VALUES('Sengiley', 81);
INSERT INTO cities(city, regionid) VALUES('Ulyanovsk', 81);

INSERT INTO cities(city, regionid) VALUES('Berdsk', 82);
INSERT INTO cities(city, regionid) VALUES('Bolotnoye', 82);
INSERT INTO cities(city, regionid) VALUES('Cherepanovo', 82);
INSERT INTO cities(city, regionid) VALUES('Chulym', 82);
INSERT INTO cities(city, regionid) VALUES('Iskitim', 82);
INSERT INTO cities(city, regionid) VALUES('Karasuk', 82);
INSERT INTO cities(city, regionid) VALUES('Kargat', 82);
INSERT INTO cities(city, regionid) VALUES('Kupino', 82);
INSERT INTO cities(city, regionid) VALUES('Kuybyshev', 82);
INSERT INTO cities(city, regionid) VALUES('Novosibirsk', 82);
INSERT INTO cities(city, regionid) VALUES('Ob', 82);
INSERT INTO cities(city, regionid) VALUES('Tatarsk', 82);
INSERT INTO cities(city, regionid) VALUES('Toguchin', 82);

INSERT INTO cities(city, regionid) VALUES('Ardon', 83);
INSERT INTO cities(city, regionid) VALUES('Beslan', 83);
INSERT INTO cities(city, regionid) VALUES('Digora', 83);
INSERT INTO cities(city, regionid) VALUES('Mozdok', 83);
INSERT INTO cities(city, regionid) VALUES('Vladikavkaz', 83);
